name: think_of_a_number
description: "Number Guesser Game"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.4+5

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  google_mobile_ads: ^5.2.0
  fluttertoast: ^8.2.8
  google_fonts:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
